### ISSUE TITLE
Trip JSON Issue

### ISSUE THREAD

**Issue by DanCosta88** [openamat/Products#1]
Ciao @dlion,

sembra esserci un errore di formattazione con il JSON relativo ai Trips.
JSON Editor Online mi restituisce questo:

```
Error: Parse error on line 1:
...},{"route_id":"246","s
-----------------------^
Expecting 'STRING', got 'undefined'

```

Grazie!! ;-)

**Comment by dlion** [comment]
@DanPhyxius Hai chiuso perché hai risolto ?

**Comment by DanCosta88** [comment]
@dlion Si! Sembra fosse un problema legato alla vecchia versione del JSON, mi son accorto che dopo il deploy si è fixato!! ;-) (o magari era un problema temporaneo non dovuto al JSON!)
